name: flutter_helloo_world
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  carousel_slider: ^4.0.0
  firebase_auth: ^4.17.8
  firebase_core: ^2.30.0
  firebase_database: ^10.4.9
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  url_launcher: ^6.0.12
  http: ^1.2.0
  image_picker: ^0.8.4+3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  file_picker: ^4.0.0
  path_provider: ^2.0.11
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
