// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH8KGUjZ32ecb34UMUlL9jm0hA6cD_nR8',
    appId: '1:485364401816:web:d5d60932ad0509145432ed',
    messagingSenderId: '485364401816',
    projectId: 'project4-bmth',
    authDomain: 'project4-bmth.firebaseapp.com',
    databaseURL: 'https://project4-bmth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project4-bmth.appspot.com',
    measurementId: 'G-CYDKCYCB6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsne3iRCo57Shf8JDdgUTu3_UCOF4u8Ow',
    appId: '1:485364401816:android:040ddc1af035f3e65432ed',
    messagingSenderId: '485364401816',
    projectId: 'project4-bmth',
    databaseURL: 'https://project4-bmth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project4-bmth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALARC7oxPKUzNDpRdLi6iKTB-6Cwj7XWE',
    appId: '1:485364401816:ios:9d993b6ff2e162a25432ed',
    messagingSenderId: '485364401816',
    projectId: 'project4-bmth',
    databaseURL: 'https://project4-bmth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project4-bmth.appspot.com',
    iosBundleId: 'com.example.flutterHellooWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALARC7oxPKUzNDpRdLi6iKTB-6Cwj7XWE',
    appId: '1:485364401816:ios:9d993b6ff2e162a25432ed',
    messagingSenderId: '485364401816',
    projectId: 'project4-bmth',
    databaseURL: 'https://project4-bmth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project4-bmth.appspot.com',
    iosBundleId: 'com.example.flutterHellooWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH8KGUjZ32ecb34UMUlL9jm0hA6cD_nR8',
    appId: '1:485364401816:web:46db4750f43095a05432ed',
    messagingSenderId: '485364401816',
    projectId: 'project4-bmth',
    authDomain: 'project4-bmth.firebaseapp.com',
    databaseURL: 'https://project4-bmth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project4-bmth.appspot.com',
    measurementId: 'G-SZZ3VDJ3CP',
  );
}
